### ISSUE TITLE
大佬你好，能不能增加 百听听书 爬虫？

### ISSUE THREAD

**Issue by yonggedebaqi** [yoval/lrts#2]
大佬你好，能不能增加 百听听书 爬虫？

**Comment by yoval** [comment]
可以通过书籍ID找到音频ID：
https://www.bookting.cn/api/book?id=505
![image](https://user-images.githubusercontent.com/20494844/65381514-9aabf580-dd25-11e9-87f0-6b8dd0db2487.png)

用过音频ID找到下载链接：
https://www.bookting.cn/api/download?type=section&id=60223
![image](https://user-images.githubusercontent.com/20494844/65381517-b9aa8780-dd25-11e9-8519-e25981d190c1.png)

**Comment by yonggedebaqi** [comment]
付费也能这样爬取？

**Comment by yonggedebaqi** [comment]
要是有python模拟登陆 下载就比较好呢。

**Comment by yonggedebaqi** [comment]
谢谢！！！弄好了
