### ISSUE TITLE
请大侠修复lrts这个VIP专辑下载

### ISSUE THREAD

**Issue by yonggedebaqi** [yoval/lrts#7]
访问这个https://m.lrts.me/ajax/getAlbumAudios?ablumnId=87982&sortType=0提取到section":202 参数作为请求，
再把section":202传入到[]中
https://m.lrts.me/ajax/getPlayPath?entityId=87982&entityType=2&opType=1&sections=[202]&type=0
希望大侠修复。

**Comment by yoval** [comment]
增加lrts_album.py下载专辑，暂未整合。

**Comment by yonggedebaqi** [comment]
多谢大侠
